### ISSUE TITLE
Slashes in TTYPEn are not handled

### ISSUE THREAD

**Issue by ptallada** [astrolabsoftware/spark-fits#105]
Hi,

While trying to read a bunch of FITS files, it fails complaining they have duplicated column names, as it cuts the column name to the value before the slash. An extract of the header:

```
TTYPE8  = 'lsst/u_MEAN'                                                         
TFORM8  = 'E       '                                                            
TTYPE9  = 'lsst/g_MEAN'                                                         
TFORM9  = 'E       '                                                            
TTYPE13 = 'euclid/VIS_MEAN'                                                     
TFORM13 = 'E       '                                                            
TTYPE14 = 'euclid/Y_MEAN'                                                       
TFORM14 = 'E       '                                                            
```
The binary table extension documentation, for the TTYPEn keyword states:

> The value field for this indexed keyword shall contain a  character string, giving the name of field n. It is recommended that only letters, digits, and underscore (hexadecimal code 5F, ``_'') be used in the name. String comparisons with the values of TTYPEn keywords should not be case sensitive. The use of identical names for different fields should be avoided.

So slashes are not recommended, but also neither excluded nor forbidden :)

**Comment by ptallada** [comment]
No worries, I'm watching your talk ;)

**Comment by JulienPeloton** [comment]
Yeah -- I saw your name entering in the room, which triggered me a reminder for this issue :-)

**Comment by JulienPeloton** [comment]
The part of the faulty code is here:

https://github.com/astrolabsoftware/spark-fits/blob/6062b7899a775ab3e60d3dee816f56c9e0eee5c1/src/main/scala/com/astrolabsoftware/sparkfits/FitsLib.scala#L93-L106

We use `/` to get individual rows of the header (they act as separators as far as I remember). Let me see what I can do (I need to refresh my memory about the header structure).

**Comment by ptallada** [comment]
AFAIK, headers are composed of "cards", 80 bytes each. Each card contains a key and a value, separated by =, and a comment which is separated by /

https://docs.astropy.org/en/stable/io/fits/usage/headers.html
