### ISSUE TITLE
DataFrame reader cannot load files as list of paths or comma separated string of paths

### ISSUE THREAD

**Issue by jacobic** [astrolabsoftware/spark-fits#62]
I am aware the hadoop file system implemented in spark-fits uses globs to load multiple files, however it does not seem to work with a list of paths or a comma separated string of paths.

 Would it be possible to add the ability to load fits files in this way? 
It seems fairly standard among spark dataframe readers so would be super useful :)

(see https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=load#pyspark.sql.DataFrameReader.load) .

# This works
```
 files = 'wmap.cluster.*.projected.fits'
 df = sqlc.read.format("fits").option("hdu", 1).load(files)
```

# This does not work:
```
 # For testing purposes limit number of files (massive speed up).
 files = glob.glob('wmap.cluster.*.projected.fits')[:3]
 # files = <class 'list'>: ['/u/jacobic/magneticum/src/../data/interim/wmap.cluster.453315a6-bd26-a929-2963-b33df1bfccfb.projected.fits', '/u/jacobic/magneticum/src/../data/interim/wmap.cluster.7dff7815-5881-b2cf-8f19-b1a3fe08e949.projected.fits', '/u/jacobic/magneticum/src/../data/interim/wmap.cluster.d77d7156-41cd-89f5-4d07-a60ef45a1934.projected.fits']

 df = sqlc.read.format("fits").option("hdu", 1).load(files)
```

# This also does not work:
```
 # For testing purposes limit number of files (massive speed up).
 files = ','.join(glob.glob('wmap.cluster.*.projected.fits')[:3])
 # files = /u/jacobic/magneticum/src/../data/interim/wmap.cluster.453315a6-bd26-a929-2963-b33df1bfccfb.projected.fits,/u/jacobic/magneticum/src/../data/interim/wmap.cluster.7dff7815-5881-b2cf-8f19-b1a3fe08e949.projected.fits,/u/jacobic/magneticum/src/../data/interim/wmap.cluster.d77d7156-41cd-89f5-4d07-a60ef45a1934.projected.fits

 df = sqlc.read.format("fits").option("hdu", 1).load(files)
```

Cheers,
Jacob

**Comment by JulienPeloton** [comment]
Hi Jacob, yes I can add these!
Actually, I had it in the corner of my mind for a long time, but never took the time to implement it satisfactorily. That shouldn't be too hard to add -- and I will let you know when the patch is ready.

**Comment by JulienPeloton** [comment]
I have created a patch at #63 (branch `inputPath`). Could you test it for your purpose?

Note that I have added only the possibility to load comma-separated files. The "list of files" case turns out to be more difficult to handle given the spark-fits structure - and it is simpler to concatenate the items of the list on the user side directly:

```python
# Input list of FITS files
list_of_files = ["f1.fits", "f2.fits", ...]

# Comma-separated
list_of_files_as_string = ','.join(list_of_files)

# DataFrame
df = spark.read.format("fits").option("hdu", 1).load(list_of_files_as_string)
```

**Comment by jacobic** [comment]
It works perfectly! thanks very much

**Comment by JulienPeloton** [comment]
Great, thanks! I will soon make a new release of the package which will include the last changes (#59, #60, #63).
