### ISSUE TITLE
Bad mapping between scalars (SPARK) and 1element vector (FITS)

### ISSUE THREAD

**Issue by marcol480** [astrolabsoftware/spark-fits#78]
**Describe the issue**
When reading a FITS file containing 1element vector this is mapped onto a 1element vector but it should be a scalar instead. 

**Expected behaviour**
It should be a scalar instead

**Actual behaviour**
Wrong mapping (see above)

**Additional context**
This issue was absent in version 0.7.3 and present in version 0.8.0

**Comment by JulienPeloton** [comment]
Thanks @marcol480 for reporting this issue! It has been fixed in #79.
