### ISSUE TITLE
Nans are present even after filtering out nans when reading large fits files (~1GB)

### ISSUE THREAD

**Issue by jacobic** [astrolabsoftware/spark-fits#96]
Hi Julien,

I hope you are keeping well and healthy :) 

I was wondering if you could help me with a `spark-fits` issue that I have been having when reading large fits files ~1GB (e.g. https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr8/north/sweep/8.0/sweep-100p030-110p035.fits). 

It seems that even when I remove all nans from the dataframe, there still appears to be nans present when a collect/show/toPandas is called. The fraction of nans is small (<0.1%) but it does cause some dataloss and means that I have to filter the data a second time after the collection from the jvm. This issue also causes summary / aggregation statistics etc. to be incorrect.

# Troubleshooting

The issue is random and therefore different elements of the dataframe are impacted each time the same collect/show/toPandas call is made with the same file and the same dataframe. This also means the total number of nans changes each time. The data is read directly from the fits file(s) using `spark-fits` each time the call is made (rather than a cached dataframe) which is why I think the fits reading stage could be causing the problem. 

Perhaps it is related to how `spark-fits` splits up the file. I have tried various record length settings (recordlength=1 * 1024, recordlength=10 * 1024, recordlength=100 * 1024) but I am not sure what is optimal or if it could alleviate this issue.

The columns that I filter on are ` mag_*`, which I derive from FLUX_* and FLUX_IVAR_* columns in the example fits file using a simple pyspark SQL expression. 

I filter out the following cases for each `mag_*` column.

```
'mag_* > 27.0'
'mag_* <= 0.0'
'isnan(mag_*)'
'isnull(mag_*)'
```

These expressions are evaluated successfully and appear in the logical plan. However, on collection, some nans which should not be there have somehow been genereated. The same code also works with smaller fits files.

I also checked to see if any columns were incorrectly casted as` DecimalType()` (as this could also cause nans due to being incorrectly casted as the numpy object dtype). But since I explicitly cast all FLUX_* and FLUX_IVAR_* columns as `FloatType()`, the resulting `mag_*` columns are also `FloatType()` so this is not the cause of the problem. 

Please let me know if you have any idea what could be causing this problem or if you require any more detailed screenshots/code samples to help troubleshoot. 

I thought it could be related to this spark-fits bug I raised last year https://github.com/astrolabsoftware/spark-fits/issues/84

> Thanks @jacobic, it helps a lot to understand. 
> 
> Actually, I dig deep inside spark-fits. When the file is read on my computer, basically it makes chunks of 33,554,432 bytes. Guess what? 33,554,432 is very close to 162829 [row] * 206 [bytes/row]... So it seems there is a mismatch in the starting index when reading a new chunk of this file. Looking deeper, I found the bug... The bug was introduced by an ugly fix for Image HDU:
> 
> https://github.com/astrolabsoftware/spark-fits/blob/5d8a1e2927011b9f23ecad3a25cd012ed755ee5d/src/main/scala/com/astrolabsoftware/sparkfits/FitsRecordReader.scala#L242-L256
> 
> I'm still not 100% sure this is the final word, but fixing it seems to give correct answer:
> 
> ```python
> # +-------+--------------------+-------------------+---------+------------------+------------------+------------------+------------------+------------------+-------------------+-----------+
> # |summary|           object_id|              d_pos|    d_mag|        specz_name|          specz_ra|         specz_dec|    specz_redshift|specz_redshift_err|specz_original_flag|specz_mag_i|
> # +-------+--------------------+-------------------+---------+------------------+------------------+------------------+------------------+------------------+-------------------+-----------+
> # |  count|             2299625|            2299625|  2299625|           2299625|           2299625|           2299625|           2299625|           2299625|            2299625|    2299625|
> # |   mean|4.325592616529654...|0.20328246733677513|      NaN|              null|157.35647009225943|2.6757728602627218|0.6220279768352934|               NaN| 2.8340504323962143|        NaN|
> # | stddev|8.044115412593749E15|0.19084386174782547|      NaN|              null|119.00443164434095|12.329133357718852|1.1161051065508547|               NaN| 23.447103620806015|        NaN|
> # |    min|   36407037608854089|        5.951991E-4|-Infinity| 3DHST_AEGIS_10002|           6.86E-4|         -7.282074|          -9.99999|               0.0|                 -1|  -9999.166|
> # |    max|   76557903720366950|          1.0048198|      NaN|ZCOSMOS-DR3-950074|         359.99936|         56.899819|            9.9999|               NaN|                B,1|        NaN|
> # +-------+--------------------+-------------------+---------+------------------+------------------+------------------+------------------+------------------+-------------------+-----------+
> ```
> 
> I will make a fix tomorrow.
> 
> _Originally posted by @JulienPeloton in https://github.com/astrolabsoftware/spark-fits/issues/84#issuecomment-501039589_

Thanks as always,

Jacob

**Comment by JulienPeloton** [comment]
Hi Jacob,

Thanks for the detailed report as usual!

If I understand correctly, the problem seems to appear on derived quantities `mag_*`. Does it appear also when you deal only with original quantities like `FLUX_*`?

Would you have a simple code that would reproduce the problem? This would help me to target the troublemaker.

Thanks!

**Comment by jacobic** [comment]
Hi Julien,

Thanks for the quick response.

I will produce a minimal reproducible example with screenshots this afternoon.
Thanks for the quick the quick response, I am looking forward this.

Cheers,
Jacob

**Comment by jacobic** [comment]
Hi Julien,

I am unable to reproduce this at the moment using a minimal example that calculates the summary statistics for hundreds of large fits file ingested at once (929493796 rows in total), even when transforming the data into magnitudes and filtering out elements using the same expressions as before. I have repeated this with recordlengths 1*1024, 10*1024 and 100*1024 and the results are consistent (and correct) every time.

This to me suggests the problem might occur from an aggregation/shuffle operation at a later stage in my pipeline (since the nans appear in random elements each time). It is strange that these columns are not modified after the same transformation and cleaning as in my minimal example yet still randomly contain nans even after the columns are cleaned. 

I will close this and continue debugging. Sorry for wasting your time!

**Comment by JulienPeloton** [comment]
No worry - do not hesitate to re-open the issue if you feel the error comes from spark-fits.

Concerning the `recordlengths` option, its value should not affect the results. This parameter is only driving the throughput (the default value seems optimal in most cases regarding buffer calls vs garbage collector calls - and it is adapted internally according to the FITS row size).
